ALTER TABLE rulesets 
    ADD COLUMN IF NOT EXISTS schedule_cron TEXT,
    ADD COLUMN IF NOT EXISTS schedule_tz TEXT NOT NULL DEFAULT 'UTC',
    ADD COLUMN IF NOT EXISTS schedule_enabled BOOLEAN NOT NULL DEFAULT FALSE;